apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_PASSWORD: "Sonukumar1"
  JWT_SECRET: "myverysecretkey123"
  CLOUDINARY_CLOUD_NAME: "dpctwrls"
  CLOUDINARY_API_KEY: "958193679768248"
  CLOUDINARY_API_SECRET: "CbJHKKaRQh-79xmPVuADiuVs7Yw"
